spring.application.name=Ticket-Allocation

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_engine
spring.datasource.username=sanyam
spring.datasource.password=Sanyam@2001

spring.jpa.hibernate.ddl-auto=create
spring.main.banner-mode=off


#spring.jpa.show-sql=true
#
#spring.jpa.properties.hibernate.format_sql=true

jwt.secret=5eae09ed-7643-45b0-beab-41f22175a93d
jwt.expiration=3600000


spring.jpa.open-in-view=false

spring.profiles.active=dev
